#:schema node_modules/wrangler/config-schema.json
name = "opengame"
main = "dist/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-25"

assets = { directory = "./public" }

kv_namespaces = [
  { binding = "KV_STORAGE", id = "7ca58075ccd54315b82982f3c8d0e32d" }
]

[define]
"process.env.REMIX_DEV_ORIGIN" = "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[vars]
ACTOR_KIT_HOST = "opengame.org"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Remix"]

[observability]
enabled = true
