#:schema node_modules/wrangler/config-schema.json
name = "opengame-org"
main = "dist/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public" }

[define]
"process.env.REMIX_DEV_ORIGIN" = "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[vars]
ACTOR_KIT_HOST = "opengame.org"
DISCORD_PUBLIC_KEY = "your_discord_public_key_here"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "USER"
class_name = "User"

[[kv_namespaces]]
binding = "KV_STORAGE"
id = "1ee406ae8ebf4b50947e68fd76633452"
preview_id = "bdf34d64eebc4555bdaf08b3c7273e95"

[[migrations]]
tag = "v1"
new_classes = ["Remix", "User"]

[observability]
enabled = true